# Generated by Django 3.2.9 on 2021-12-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForexTestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_refresh', models.DateTimeField()),
                ('currency', models.CharField(max_length=50)),
                ('amount', models.IntegerField(max_length=50)),
            ],
        ),
    ]
