# Generated by Django 3.2.9 on 2022-02-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatesByPairs',
            fields=[
                ('pair', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('last_refreshed', models.DateTimeField()),
                ('exchange_rate', models.FloatField(null=True)),
            ],
            options={
                'unique_together': {('pair', 'last_refreshed')},
            },
        ),
    ]
