# Generated by Django 3.2.9 on 2021-12-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forextesttable',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
